version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - java_app
    networks:
      - expense-app-nw

  java_app:
    build:
      context: .
    container_name: "expenseapp"
    networks:
      - expense-app-nw
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Test@123"
    depends_on:
      - mysql_db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "8080:8080"
    restart: always

  mysql_db:
    image: mysql
    container_name: "mysql"
    networks:
      - expense-app-nw
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: expenses_tracker
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pTest@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  expense-app-nw:

volumes:
  mysql-data: